-- This SQL file drops all tables in the current database
-- Run this to completely reset the database

DROP TABLE IF EXISTS "EventRecipe" CASCADE;
DROP TABLE IF EXISTS "CraftingTransaction" CASCADE;
DROP TABLE IF EXISTS "CraftingRecipe" CASCADE;
DROP TABLE IF EXISTS "Event" CASCADE;
DROP TABLE IF EXISTS "PvPCombatLog" CASCADE;
DROP TABLE IF EXISTS "PvPMatch" CASCADE;
DROP TABLE IF EXISTS "Breach" CASCADE;
DROP TABLE IF EXISTS "Notification" CASCADE;
DROP TABLE IF EXISTS "Leaderboard" CASCADE;
DROP TABLE IF EXISTS "OfflineCache" CASCADE;
DROP TABLE IF EXISTS "BuyOrder" CASCADE;
DROP TABLE IF EXISTS "MarketListing" CASCADE;
DROP TABLE IF EXISTS "Transaction" CASCADE;
DROP TABLE IF EXISTS "Inventory" CASCADE;
DROP TABLE IF EXISTS "ItemDefinition" CASCADE;
DROP TABLE IF EXISTS "VaultUpgrade" CASCADE;
DROP TABLE IF EXISTS "Vault" CASCADE;
DROP TABLE IF EXISTS "PlayerProfile" CASCADE;
DROP TABLE IF EXISTS "Session" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;
